Feature/color-palette
Arthutu/letreiro pull request #6
Opened 2022-03-03 01:18 UTC by vitormrp

- Custom theme applied with selected colors. 
- Dark/Light mode toggle button was added to the header.
- Color blind mode switch button was added to settings modal.

2022-03-03 23:05 UTC, Arthutu commented on src/common/components/letter.tsx
> +import {
Está sendo usado?

2022-03-03 23:08 UTC, Arthutu commented on src/common/components/theme.tsx
> +import { PaletteMode, ThemeOptions } from "@mui/material";
Isso aqui na verdade não é um componente, eh mais uma helper. Acho que seria melhor jogar ele pra common/utils/theme.utils.ts

2022-03-03 23:10 UTC, Arthutu commented on src/common/enum/letter-status.enum.ts
> +};
Tá sendo usado?

2022-03-03 23:21 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  const [mode, setMode] = React.useState<PaletteMode>("dark");
acho que o nome pode ser paletteMode, setPalleteMode, fica mais claro pra qm bate o olho de qq se trata esse mode

2022-03-03 23:22 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  );
Esse trem aqui tá formatado direitinho e precisa mesmo ter () => () => {} da linha 23?

2022-03-03 23:23 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  const [colorBlind, setColorBlind] = React.useState<boolean>(false);
Aqui pode usar só useState, sem o React. na frente

2022-03-03 23:23 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  const colorMode = React.useMemo(
Aqui pode usar só useMemo, sem o React. na frente

2022-03-03 23:23 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  const colorBlindMode = React.useMemo(
Aqui pode usar só useMemo, sem o React. na frente

2022-03-03 23:24 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  );
Mesma coisa do outro comentário, tá formatado direito e precisa do () => () => {} ?

2022-03-03 23:24 UTC, Arthutu commented on src/modules/letreiro-app.tsx
> +  const theme = React.useMemo(
Aqui pode usar só useMemo, sem o React. na frente

2022-03-03 23:26 UTC, Arthutu commented on src/modules/word-grid/components/styles.module.css
> +/* TODO: SET CSS VARIABLES FOR COLORS (WHEN USING LIGHT THEME SECONDARY ISN'T #797979, THEREFORE THE BACKGROUND CHANGES A LITTLE BIT DURING ANIMATIONS) */
Isso aqui vc fez, não?

2022-03-03 23:28 UTC, Arthutu requested changes
Waiting comments to be resolved.

2022-03-04 13:35 UTC, vitormrp commented on src/modules/letreiro-app.tsx
> +  );
Também achei estranho, mas foi o jeito que deu certo do context funcionar

2022-03-04 13:51 UTC, vitormrp commented on src/common/enum/letter-status.enum.ts
> +};
Ta sim, no current-word-row e content do helper modal

2022-03-07 22:24 UTC, merged